### ISSUE TITLE
Feature addition?

### ISSUE THREAD

**Issue by nzminecraftDOTcom** [Jochyoua/MCSF#1]
Is it possible to have the offending word or message blocked entirely on output to external platforms, e.g DiscordSRV seeing as the swear filter doesn't "stop" swearing only hides the words. 

A default toggle stauts "on or off" would be nice in the config, as I had to enable it and would prefer it to be enabled by default (makes sense)

Are these possible?

**Comment by Jochyoua** [comment]
Actually, believe it or not I have been working on a default enable feature
and a feature that makes it so the player cannot toggle the swear filter at
all. Also, I'll see what I can do about the discordsrv thing ;) I've been
away for a while and I've almost got just about everything covered for an
update. I've been trying to do something about signs as well.

**Comment by Jochyoua** [comment]
Features have been added, sorry for the late reply. :)
