### ISSUE TITLE
Massive spikes of TPS loss when players join. 1.13.2

### ISSUE THREAD

**Issue by Weasel-Beans** [Jochyoua/MCSF#2]
https://timings.aikar.co/?id=6f3c22aaf4314f40ad808eb4fbff5b8a

I noticed huge spikes of TPS loss in the timings reports I've looked at since downloading the new version of this plugin. It mainly happens when players join and seems to be connected to MCSF. I hope this will be useful in some way.

Edit: After configuring the plugin and restarting, there is less TPS loss after turning off sign/book checking etc, but still more than I expected from "MCSF::Task: com.github.Jochyoua.MCSF.Main$1 (interval:1)"

Here's another report from moments ago:
https://timings.aikar.co/?id=2ddaa80deb234b388c52a27640966095

**Comment by Jochyoua** [comment]
This is caused by me neglecting to realize that looping through all the signs constantly and expecting nothing bad to happen. I've since removed any sign checks until further notice, thank you very much <3
