### ISSUE TITLE
/mcsf reload not working

### ISSUE THREAD

**Issue by t0mtee** [Jochyoua/MCSF#4]
Doing /mcsf reload just brings up the command list

**Comment by Jochyoua** [comment]
I had removed that command in a previous update since it didn't work
correctly, once I have the time I'll re-add it i thought I removed all
documentation I apologize

**Comment by Jochyoua** [comment]
Fixed in version [5.0](https://github.com/Jochyoua/MCSF/releases/tag/5.0)
