### ISSUE TITLE
Data saves to config.yml even with mysql enabled

### ISSUE THREAD

**Issue by Alexz1008** [Jochyoua/MCSF#5]
This isn't necessarily a bug, but since this plugin automatically saves every player's swear filter data into the config.yml, that file gets very big very fast, and once it reaches a critical mass, it's going to lag every time a new player joins.

This can be easily fixed by simply saving the data in ONLY the sql database instead, but for some reason even when mysql connection is successful, it still saves to config as well. I would much appreciate if it only saved to config if sql was not a viable option to save to. This is the literal only problem in an otherwise surprisingly reliable and well-made plugin. Please let me know if you can fix this!

**Comment by Jochyoua** [comment]
I can see what I can do about that, thank you for the post. Currently, I have it set so that once the player joins the data is set and whenever the data is needed the server would call from the file instead of accessing the database. I don't know about it lagging every time a player would join but I'll look into that.

**Comment by Alexz1008** [comment]
There is no guarantee that it will lag, but I get roughly a thousand players a month, and I once had a plugin that stored data the same way (all in one file), and it started lagging very badly once it reached some critical point. It's true that it's possible it won't lag (I have no proof), but I worry about adding this plugin permanently before I'm sure. I appreciate the understanding!

**Comment by Jochyoua** [comment]
Fixed in  [release 5.1](https://github.com/Jochyoua/MCSF/releases/tag/5.1)
